### ISSUE TITLE
Missing sub-modules on update user agent action

### ISSUE THREAD

**Issue by Giglium** [Giglium/vinted_scraper#40]
## Describe the bug
As we can see on this failed GitHub Action: https://github.com/Giglium/vinted_scraper/actions/runs/7737106373, the checkout action of [update-user-agents.yml](https://github.com/Giglium/vinted_scraper/blob/main/.github/workflows/update-user-agents.yml) should be:
```yaml
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
```

This is required to download the submodules necessary to execute the makefile action.

## Steps to reproduce

1. Re-run the Github Action

## Expected behavior

Update the user agent file and open the PR
